### ISSUE TITLE
추가 구현 사항

### ISSUE THREAD

**Issue by Jaehui-Lee** [Jaehui-Lee/CLI-Excel#1]
## 설명
추가 구현 사항 (11/12 회의)

## TODO

- [ ] 프로그램 시작 시, 터미널 사이즈 변경
    * Mac OS, UNIX 명령어 >> printf '\033[8;4-;120t' 사용
    * Window, ??

- [x] 표 출력 시, 표가 연결되게 출력하기

- [ ] 표에서 상하좌우 스크롤 기능 구현

- [ ] 엑셀 함수 구현

- [ ] txt 파일로 저장 및 열기

- [ ] manual 구현

- [x] sheet number 표시

**Comment by Jaehui-Lee** [comment]
* sheet number 표시
excel->print_table() 함수에 excellist의 current_page와 excel_count 값을 전달해서
table 출력 시, 우측 하단에 같이 출력되도록 표시

**Comment by plug4564** [comment]
>

**Comment by plug4564** [comment]
``

**Comment by Jaehui-Lee** [comment]
* Add 8 Excel Functions
  * SUM : Add the values of cells within the input range
  * AVG : Average of values of cells within the input range
  * PRODUCT : Multiply values of cells within the input range
  * COUNT : Number of cells with entered values
  * MIN / MAX : Smallest / Largest number within the input range
  * RAND / RANDBETWEEN : 0~100 / random value within the input range

```
void FuncCell::parse_function()
{
    /*
    ...
    similar to before
    ...
    */
    calculate();
}

// Calculate the value of the parsed function
void FuncCell::calculate()
{
    // Implemented
}
```

**Comment by Jaehui-Lee** [comment]
* Add to_txt() function
  * Call to_txt() function in order of (class) ExcelList -> Excel -> Table

```
void ExcelList::to_txt(string to)
{
    ofstream writeFile(to.data());
    if (writeFile.is_open())
    {
        writeFile << excel_count << endl;
        list<Excel *>::iterator iter;
        int i = 1;
        for (iter = excelList.begin(); iter != excelList.end(); iter++)
        {
            (*iter)->to_txt(writeFile, i++);
        }
    }
    writeFile.close();
}
```
```
void Excel::to_txt(ofstream& writeFile, int current_excel)
{
    writeFile << current_excel << " ";
    current_table->to_txt(writeFile);
}
```
```
void Table::to_txt(ofstream& writeFile)
{
    // implemented
    // output table data
    // format : CellName DataType value ( value can be expression or function )
}
```

**Comment by Jaehui-Lee** [comment]
* File open
  * Add from_txt() function
    * Call from_txt() function in order of (class) main -> ExcelList -> Excel

```
int main()
{
...
/*
      Get filename
      Call excelList.from_txt(filename)
      Execute Excel
*/
...
}
```
```
bool ExcelList::from_txt(string from)
{
/*
      File open and create window(excel)
*/
}
```
```
void Excel::from_txt(ifstream& readFile)
{
/* 
      Read data from file
      Create data by type 
*/ 
}
```

**Comment by sorkrkwlsrjtemf** [comment]
#scroll function

* 문제점 : ncurses 라이브러리를 활용하여 scroll 기능을 탐구했을때, scroll bar 형태의 구현이 어려운 것으로 파악됨.
* 대안책 : scroll bar 형태의 구현 대신 화면을 분할하여 입력에 따라 scroll처럼 보여주는 형태로 구현하기 위해 시도하기로 함.
* manual page에 적용하여 scroll 구현 후 excell page에 이를 활용하여 적용.
