### ISSUE TITLE
Sort command

### ISSUE THREAD

**Issue by plug4564** [Jaehui-Lee/CLI-Excel#5]
## 설명
엑셀 내에서 Sort명령어 구현
해당 셀 영역에서 데이터가 존재하는 셀들을 오름차순 또는 내림차순으로 재정렬한다.
ex) sort(A1:A10), sort(A1:A10) desc, sort(B5:T5) acs

## TODO
- [ ] 해당 셀 영역 파싱
- [ ] 셀 데이터 유무 판단
- [ ] 셀 데이터 추출 및 정렬

**Comment by plug4564** [comment]
각 Cell type에 따라 value를 읽은 후 FuncCell과 ExprCell type의 경우 data도 함께 읽는다.
value를 알고리즘을 통해 배열 시킨 후 각 Cell type에 맞게 value와 data를 쓴다.
