### ISSUE TITLE
Error Handling

### ISSUE THREAD

**Issue by Jaehui-Lee** [Jaehui-Lee/CLI-Excel#7]
## 설명
Error Handling

## TODO
- [ ] command (ex. setn, sets, ..., find, goto, ...) error check
- [ ] cell name (ex. A1, A1:A5, ...) error check
- [ ] value (ex. number format, date format, expression format, function format, ...) error check
