### ISSUE TITLE
DONE / TODO

### ISSUE THREAD

**Issue by Jaehui-Lee** [Jaehui-Lee/CLI-Excel#8]
## 설명
추가된 기능 및 구현할 기능들 구분

## DONE
- [ ] FileManager (File open, File navigation)
- [ ] Remove Cell
- [ ] Overall Table Structure Modification
- [ ] Set value based on range
- [ ] Moving Table using Arrow Keys

## TODO
- [ ] Auto Save (thread, every 30sec)
- [ ] Undo
- [ ] Sort
- [ ] Manual

... More
